#!/usr/bin/env python3
"""Backfill missing priced fighters with evidence-verified Wikipedia careers.

A page is accepted only when its professional record contains at least one exact
archived-odds matchup by full date + normalized opponent name. This is a
supplemental research layer; ambiguous search results are retained as failures,
never guessed.
"""
from __future__ import annotations
import argparse,datetime as dt,json,re,sqlite3,sys,time,unicodedata,urllib.parse,urllib.request
from pathlib import Path
from bs4 import BeautifulSoup
ROOT=Path(__file__).resolve().parent
COLLECTORS=ROOT.parent/'collectors';sys.path.insert(0,str(COLLECTORS))
from wiki_record_tables import record_tables,record_date
DB=ROOT/'boxing.sqlite3'
OUT=ROOT.parent/'supplemental_careers'/'verified_priced_careers.jsonl'
UA='Mozilla/5.0 AppwizaBoxingCareerBackfill/1.0'

def nk(s):
    x=unicodedata.normalize('NFKD',str(s or '')).encode('ascii','ignore').decode().lower()
    return re.sub(r'[^a-z0-9]','',x)

def get(url,timeout=35):
    req=urllib.request.Request(url,headers={'User-Agent':UA,'Accept-Language':'en-US,en;q=0.8'})
    with urllib.request.urlopen(req,timeout=timeout) as r:return r.read()

def search_titles(name):
    q=urllib.parse.urlencode({'action':'query','list':'search','srsearch':f'"{name}" boxer','srlimit':6,'format':'json','utf8':1})
    try:data=json.loads(get('https://en.wikipedia.org/w/api.php?'+q))
    except Exception:return []
    titles=[x.get('title') for x in data.get('query',{}).get('search',[]) if x.get('title')]
    # Exact title variants first, without assuming exact title proves identity.
    titles.sort(key=lambda t:(nk(t)!=nk(name),len(t)))
    return titles

def parse_page(title):
    url='https://en.wikipedia.org/wiki/'+urllib.parse.quote(title.replace(' ','_'))
    soup=BeautifulSoup(get(url),'lxml')
    info=soup.select_one('table.infobox');profile={}
    if info:
        for tr in info.find_all('tr'):
            th=tr.find('th');td=tr.find('td')
            if th and td:profile[th.get_text(' ',strip=True)]=td.get_text(' ',strip=True)
    born=soup.select_one('.bday');rows=[]
    for headers,trs in record_tables(soup):
        for tr in trs:
            cells=tr.find_all(['th','td'],recursive=False)
            if len(cells)!=len(headers):continue
            r=dict(zip(headers,[c.get_text(' ',strip=True) for c in cells]))
            result=str(r.get('result','')).casefold()
            if result not in ('win','loss','draw','nc','no contest'):continue
            try:date=record_date(r.get('date',''))
            except Exception:continue
            rows.append({'date':date,'result':result,'opponent':r.get('opponent',''),'type':r.get('type',''),
                         'round_time':r.get('round, time',''),'location':r.get('location',''),'record':r.get('record',''),
                         'raw':r})
    return {'title':title,'url':url,'born':born.get_text(strip=True) if born else None,'profile':profile,'rows':rows}

def priced_missing(con):
    known={nk(r['name']) for r in con.execute('select name from normalized_fighters') if r['name']}
    for r in con.execute("select distinct boxer_a from bouts where source='wikipedia'"):
        if r['boxer_a']:known.add(nk(r['boxer_a']))
    groups={}
    for r in con.execute("select odds_bout_id,event_date,selection,bookmaker from priced_bout_research where result in ('WIN','LOSS')"):
        k=(r['odds_bout_id'],r['event_date']);g=groups.setdefault(k,{'names':set(),'quotes':0,'books':set()})
        if r['selection']:g['names'].add(str(r['selection']).strip())
        g['quotes']+=1;g['books'].add(r['bookmaker'])
    miss={}
    for (bid,date),g in groups.items():
        if len(g['names'])!=2:continue
        a,b=sorted(g['names'])
        for target,opp in ((a,b),(b,a)):
            if nk(target) in known:continue
            x=miss.setdefault(target,{'name':target,'evidence':[],'bouts':set(),'quotes':0,'books':set()})
            x['evidence'].append({'odds_bout_id':bid,'date':date,'opponent':opp})
            x['bouts'].add((bid,date));x['quotes']+=g['quotes'];x['books'].update(g['books'])
    ranked=[]
    for x in miss.values():
        x['priced_bouts']=len(x.pop('bouts'));x['bookmakers']=len(x.pop('books'))
        # de-dupe evidence generated by bookmaker rows
        x['evidence']=[dict(t) for t in {tuple(sorted(e.items())) for e in x['evidence']}]
        ranked.append(x)
    ranked.sort(key=lambda x:(-x['priced_bouts'],-x['quotes'],x['name']))
    return ranked

def match_evidence(page,evidence):
    idx={(r['date'],nk(r['opponent'])) for r in page['rows']}
    return [e for e in evidence if (e['date'],nk(e['opponent'])) in idx]

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--limit',type=int,default=60);args=ap.parse_args()
    con=sqlite3.connect(DB);con.row_factory=sqlite3.Row
    OUT.parent.mkdir(parents=True,exist_ok=True)
    done={}
    if OUT.exists():
        for line in OUT.read_text().splitlines():
            try:r=json.loads(line);done[nk(r['requested_name'])]=r
            except Exception:pass
    queue=[x for x in priced_missing(con) if nk(x['name']) not in done][:args.limit]
    accepted=[];failed=[]
    for i,item in enumerate(queue,1):
        found=None;tried=[]
        for title in search_titles(item['name']):
            tried.append(title)
            try:page=parse_page(title)
            except Exception:continue
            matches=match_evidence(page,item['evidence'])
            if matches:
                found={'requested_name':item['name'],'verified_title':title,'source_url':page['url'],'born':page['born'],
                       'profile':page['profile'],'career_rows':page['rows'],'matched_price_evidence':matches,
                       'priced_bouts':item['priced_bouts'],'bookmakers':item['bookmakers'],
                       'verification':'professional record contains exact full-date + normalized-opponent priced matchup',
                       'collected_at':dt.datetime.now(dt.timezone.utc).isoformat()}
                break
        if found:
            with OUT.open('a',encoding='utf-8') as f:f.write(json.dumps(found,ensure_ascii=False)+'\n')
            accepted.append({'name':item['name'],'page':found['verified_title'],'rows':len(found['career_rows']),'matched':len(found['matched_price_evidence']),'priced_bouts':item['priced_bouts']})
        else:failed.append({'name':item['name'],'priced_bouts':item['priced_bouts'],'tried':tried})
        print(i,item['name'],'OK' if found else 'NO_MATCH',flush=True);time.sleep(.15)
    report={'attempted':len(queue),'accepted':len(accepted),'failed':len(failed),'accepted_items':accepted,'failed_items':failed,
            'total_supplemental_fighters':len(done)+len(accepted)}
    (OUT.parent/'latest_backfill_report.json').write_text(json.dumps(report,indent=2,ensure_ascii=False))
    print(json.dumps(report,indent=2,ensure_ascii=False))
if __name__=='__main__':main()
