from pathlib import Path
p=Path('scripts/nfl_live_legacy_full_dissection.py')
s=p.read_text()
old="""# Reuse exact live-rule reconstruction so this audit cannot silently drift from the scanner.\nns=runpy.run_path(str(REPO/'scripts/nfl_audit_current_live_legacy_methods.py'))\nbets=ns['bets'].copy(); rich=ns['d'].copy(); metrics0=ns['metrics']\nnum=lambda x:pd.to_numeric(x,errors='coerce')\n"""
new="""# Use the already-verified exact live-method bet lists, then enrich by game/team.\n# These files are the source behind the published 75-16 / 55-9 exact audit.\nparts=[]\nfor mid,fn in [('original','original_bets.csv'),('stricter','stricter_bets.csv')]:\n    z=pd.read_csv(REPO/'nfl/legacy_live_home_opener_exact'/fn)\n    z['method']=mid; z['team']=z['home_team']; z['opponent']=z['away_team']\n    z['moneyline']=pd.to_numeric(z['ml'] if 'ml' in z else z['home_moneyline'],errors='coerce')\n    z['profit_units']=pd.to_numeric(z['profit'],errors='coerce')\n    z['record_gap']=pd.to_numeric(z['prior_win_pct'],errors='coerce')-pd.to_numeric(z['opponent_prior_win_pct'],errors='coerce')\n    z['run_def_rank']=pd.to_numeric(z['run_rank'],errors='coerce')\n    parts.append(z)\nbets=pd.concat(parts,ignore_index=True)\n# This is the broadest current research table: coach-quality, opponent-relative coach quality,\n# football efficiency and the previously materialized pregame features used in CQ/H discovery.\nrich=pd.read_parquet(CTX/'coach_quality_expansion/coach_quality_enriched_team_sides.parquet')\nnum=lambda x:pd.to_numeric(x,errors='coerce')\n"""
if old not in s: raise SystemExit('expected legacy input block not found')
s=s.replace(old,new,1)

anchor="""joined=bets.merge(rf[['game_id','team']+featcols],on=['game_id','team'],how='left',suffixes=('','_rich'))\n\n# Add preseason form for selected team and opponent.\n"""
replacement="""joined=bets.merge(rf[['game_id','team']+featcols],on=['game_id','team'],how='left',suffixes=('','_rich'))\n# Add the dedicated pregame context store too. Keep only columns not already materialized\n# so no feature is silently overwritten.\nif CONTEXT.exists():\n    ctxall=pd.read_parquet(CONTEXT).drop_duplicates(['game_id','team'])\n    add=['game_id','team']+[c for c in ctxall.columns if c not in joined.columns and c not in {'season','week','opponent'}]\n    joined=joined.merge(ctxall[add],on=['game_id','team'],how='left')\n\n# Add preseason form for selected team and opponent.\n"""
if anchor not in s: raise SystemExit('join anchor missing')
s=s.replace(anchor,replacement,1)

old_features="""# Pregame-safe enriched features. Weather deliberately excluded per prior decision.\nprefixes=('coachq_','opp_coachq_','adv_','rank_','recent_','pre_','prior_','returning_','qb_','out_','travel_','road_','rest','fatigue','tz_','dome_game','grass_surface','base_vs_open_prob_move','preseason_','opp_preseason_')\nexclude_frag=('score','result','profit','win','closing','final','temperature','wind','weather')\nfeatures=[]\nfor c in joined.columns:\n    if c in core or c in {'market_prob','prior_games'}:continue\n    if not any(c.startswith(p) for p in prefixes):continue\n    if any(k in c.lower() for k in exclude_frag):continue\n    if num(joined[c]).notna().sum()<25:continue\n    features.append(c)\nfeatures=sorted(set(features),key=lambda c:num(joined[c]).notna().sum(),reverse=True)[:180]\n"""
new_features="""# Pregame-safe enriched feature universe. Rather than rely on name prefixes, take every\n# numeric materialized feature with meaningful coverage, then explicitly deny outcome,\n# score, closing-market, future, weather and identity fields.\nexclude_exact=set(core)|{'market_prob','prior_games','home_score','away_score','completed','tie','loss','margin','equity','drawdown','p','w','ml','espn','gsis','pff','ftn','old_game_id'}\nexclude_frag=('score','result','profit','closing','final','temperature','wind','weather','postgame','future','actual_','settlement','outcome','winner')\nfeatures=[]\nfor c in joined.columns:\n    lc=c.lower()\n    if c in exclude_exact:continue\n    if any(k in lc for k in exclude_frag):continue\n    v=num(joined[c])\n    if v.notna().sum()<25 or v.nunique(dropna=True)<2:continue\n    # IDs and raw timestamps can only encourage spurious splits.\n    if lc.endswith('_id') or lc in {'season','week'}:continue\n    features.append(c)\nfeatures=sorted(set(features),key=lambda c:(num(joined[c]).notna().sum(),num(joined[c]).nunique()),reverse=True)[:260]\n"""
if old_features not in s: raise SystemExit('feature block missing')
s=s.replace(old_features,new_features,1)

# Preserve the page-parsed week instead of replacing it with a schedule-derived week, and\n# attach all available 2026 enriched fields so confirmed vetoes can be evaluated on today's board.
s=s.replace("""openers=sch.drop_duplicates('home_team').rename(columns={'home_team':'team','away_team':'opponent'})[['game_id','team','opponent','week']]\n    cur=cur.drop(columns=['week'],errors='ignore').merge(openers,on='team',how='left')\n""","""openers=sch.drop_duplicates('home_team').rename(columns={'home_team':'team','away_team':'opponent'})[['game_id','team','opponent','week']].rename(columns={'week':'schedule_week'})\n    cur=cur.merge(openers,on='team',how='left')\n""",1)

current_anchor="""        cur=cur.merge(cx[cols],on=['game_id','team'],how='left')\n    # Base-method identity from known live board criteria, copied from page evidence when possible.\n"""
current_repl="""        cur=cur.merge(cx[cols],on=['game_id','team'],how='left')\n    try:\n        cq=pd.read_parquet(CTX/'coach_quality_expansion/coach_quality_enriched_team_sides.parquet')\n        cq=cq[(pd.to_numeric(cq.season,errors='coerce')==2026)].drop_duplicates(['game_id','team'])\n        ccols=['game_id','team']+[c for c in cq.columns if c not in cur.columns and c not in {'season','week','opponent'}]\n        cur=cur.merge(cq[ccols],on=['game_id','team'],how='left')\n    except Exception:\n        pass\n    # Base-method identity from known live board criteria, copied from page evidence when possible.\n"""
if current_anchor in s:s=s.replace(current_anchor,current_repl,1)

# After historical price data is attached, evaluate any newly confirmed enriched stack against\n# each current selection when the required 2026 feature is known.
status_anchor="""        if len(z):\n            cur.loc[i,'historical_price_bucket']=label;cur.loc[i,'price_bucket_n']=int(z.iloc[0].n);cur.loc[i,'price_bucket_win_pct']=float(z.iloc[0].win_pct);cur.loc[i,'price_bucket_roi']=float(z.iloc[0].roi);cur.loc[i,'price_bucket_recent_roi']=float(z.iloc[0].recent_roi)\n    cur.to_csv(OUT/'current_board_deep_context.csv',index=False)\n"""
status_repl="""        if len(z):\n            cur.loc[i,'historical_price_bucket']=label;cur.loc[i,'price_bucket_n']=int(z.iloc[0].n);cur.loc[i,'price_bucket_win_pct']=float(z.iloc[0].win_pct);cur.loc[i,'price_bucket_roi']=float(z.iloc[0].roi);cur.loc[i,'price_bucket_recent_roi']=float(z.iloc[0].recent_roi)\n        fd=next((q for q in final_rows if q['method']==cur.loc[i,'method']),None)\n        if not fd or not fd.get('vetoes'):\n            cur.loc[i,'enriched_veto_status']='NONE'\n        else:\n            checks=[]\n            for token in str(fd['vetoes']).split(' | '):\n                m=re.match(r'(.+?) (<=|>=) (-?[0-9.eE+]+)$',token.strip())\n                if not m: checks.append(None); continue\n                f,o,t=m.group(1),m.group(2),float(m.group(3))\n                if f not in cur.columns or pd.isna(cur.loc[i,f]): checks.append(None); continue\n                val=float(cur.loc[i,f]); checks.append(val<=t if o=='<=' else val>=t)\n            cur.loc[i,'enriched_veto_status']='TRIGGERED' if any(x is True for x in checks) else ('PASS' if checks and all(x is False for x in checks) else 'UNKNOWN')\n            cur.loc[i,'enriched_veto_rule']=fd.get('vetoes','')\n    cur.to_csv(OUT/'current_board_deep_context.csv',index=False)\n"""
if status_anchor not in s: raise SystemExit('current status anchor missing')
s=s.replace(status_anchor,status_repl,1)

p.write_text(s)
print('patched dissection to verified exact bets + broad enriched pregame universe')
