from pathlib import Path
import sys

p=Path(sys.argv[1])
s=p.read_text()
marker='CROSS_SPORT_RENDER_ISOLATION_V1'
if marker in s:
    print('shared publisher already isolated')
    raise SystemExit(0)

old="""  atomic(path,json.dumps(payload,allow_nan=False),0o600)
  render_all()
CSS='''"""
new="""  atomic(path,json.dumps(payload,allow_nan=False),0o600)
  render_sport(sport)
# CROSS_SPORT_RENDER_ISOLATION_V1
CSS='''"""
if old not in s:
    raise SystemExit('save/render_all anchor missing')
s=s.replace(old,new,1)

anchor="""def render_all():
 public=ROOT/'public';public.mkdir(parents=True,exist_ok=True);public.chmod(0o755)
 atomic(public/'style.css',CSS+'\n#downloads{margin-top:48px}#downloads summary{font-size:14px}#downloads li{overflow-wrap:anywhere}',0o644)
 for sport in ['index','ufc','nfl','boxing']:
  path=ROOT/'state'/(sport+'.json');payload=json.loads(path.read_text()) if path.exists() else None
  dest=public/'index.html' if sport=='index' else public/sport/'index.html'
  atomic(dest,page(sport,payload),0o644);dest.parent.chmod(0o755)
"""
replacement="""def render_sport(sport):
 public=ROOT/'public';public.mkdir(parents=True,exist_ok=True);public.chmod(0o755)
 atomic(public/'style.css',CSS+'\n#downloads{margin-top:48px}#downloads summary{font-size:14px}#downloads li{overflow-wrap:anywhere}',0o644)
 path=ROOT/'state'/(sport+'.json');payload=json.loads(path.read_text()) if path.exists() else None
 dest=public/'index.html' if sport=='index' else public/sport/'index.html'
 atomic(dest,page(sport,payload),0o644);dest.parent.chmod(0o755)

def render_all():
 # CROSS_SPORT_RENDER_ISOLATION_V1
 # Bulk utility refreshes only the neutral landing page and boxing.
 # UFC/NFL own enhanced pages are regenerated by their sport-specific publishers/hooks.
 for sport in ['index','boxing']:
  render_sport(sport)
"""
if anchor not in s:
    raise SystemExit('render_all anchor missing')
s=s.replace(anchor,replacement,1)
p.write_text(s)
print('shared publisher isolated by sport')
